### ISSUE TITLE
TASK: paktype-*-fonts were retired

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#134]
### What does the ELN SIG need to do?
* The paktype-naqsh-fonts, paktype-naskh-basic-fonts, and paktype-tehreer-fonts were retired yesterday in rawhide for having been orphaned for 6+ weeks, which causes them to be blocked in koji.  These packages were in the ELN package set, and therefore (due to a quirk in DBS) are showing up as "failed".
* If these packages are still wanted in RHEL 10+, then a new maintainer needs to be found to adopt them, preferably before a new package review is required.
* If these packages are no longer wanted in RHEL 10+, then they should be removed from ELN workloads in CR.
* This is not the first time this has happened to packages in the ELN set.  We need some way of noticing that a package in the ELN set is orphaned and at risk for retirement so that new maintainers can be found before it gets to this point.

/cc @hroncok who manages the orphaned package workflow.

**Comment by hroncok** [comment]
> We need some way of noticing that a package in the ELN set is orphaned and at risk for retirement so that new maintainers can be found before it gets to this point.

My very opinionated point of view: When a package is added to an RHEL workload, the RHEL maintainers should strive to become Fedora co-maintainers as well because it's *part of their job*. It is very uncommon (but not impossible) that a Fedora package maintainer would refuse an offer of help.

Once the RHEL maintainers are co-maintaining the package, when the package is orphaned, they are bcc'ed on my orphaned packages reports (which is unfortunately usually quite pointless with gmail) and they will see their orphaned packages on Fedora Packager Dashboard.

**Comment by hroncok** [comment]
Fedora Rawhide's compose is also failing because of this. https://pagure.io/releng/failed-composes/issue/5031

**Comment by yselkowitz** [comment]
Composes are fixed now.
