### ISSUE TITLE
TASK: check Fedora ELN buildroot configuration

### ISSUE THREAD

**Issue by sandrobonazzola** [fedora-eln/eln#162]
### What does the ELN SIG need to do?
Looking at Koji root logs as https://kojipkgs.fedoraproject.org//packages/libvirt/9.8.0/1.eln131/data/logs/x86_64/root.log
you can notice several packages with fc40 dist tag. Thos packages seems to come from Rawhide and are preferred to ELN ones as fc40 is greater than eln131.

As Fedora ELN has been bootsrapped I would consider dropping Rawhide repo from ELN buildroot.

**Comment by sgallagher** [comment]
Rawhide cannot be removed from the ELN buildroot because we would otherwise fail builds that add new dependencies. Our only recourse is to allow Rawhide to temporarily pull in the Fedora package. Once the package shows up in Content Resolver, the automation will rebuild it for ELN.

When performing builds in Koji, the buildroot is actually generated automatically and prioritizes the most-recently-tagged build in ELN over any other repository. Sometimes you will still see Rawhide builds for the above reason OR because up until recently (Summer 2023) we would sometimes tag the Fedora build directly to the `eln` tag for use in the buildroot of itself. Some of those historic builds remain in the tag because they haven't been rebuilt since.
