### ISSUE TITLE
procps-ng-devel missing on ELN on COPR

### ISSUE THREAD

**Issue by xambroz** [fedora-eln/eln#174]
Hello,
please I am trying to rebuild openscap package on COPR, but it fails becasue the procps-devel (AKA procps-ng-devel) package is not available in ELN:
https://download.copr.fedorainfracloud.org/results/rebus/infosec/fedora-eln-x86_64/06910641-openscap/builder-live.log.gz

But the package is there when building with Fedora KOJI (procps-ng-devel) during the openscap rebuild for ELN:
https://kojipkgs.fedoraproject.org//packages/openscap/1.3.9/5.eln134/data/logs/x86_64/root.log

On COPR Matrix forum (https://app.element.io/#/room/#buildsys:fedoraproject.org) @praiskup asked me that this github issue will be probably better place to solve the issue of not having the procps-devel resp. procps-ng-devel sub-package publicly available.

Is there anything you can do about this?

Thank you
Michal Ambroz

**Comment by sgallagher** [comment]
It's not listed in https://pagure.io/pungi-fedora/blob/eln/f/prepopulate.json which is where we indicate which packages are sorted into BaseOS, AppStream, CRB, etc.

I see that `procps-ng-devel` is shipped in CRB in CentOS Stream 9, but it seems it was dropped from CentOS Stream 10. I'm inquiring internally as to whether this was intentional or an oversight.

**Comment by sgallagher** [comment]
I got the answer that it was an oversight not having it in CRB in CentOS Stream 10, but the person who was going to update it hasn't done so.

**Comment by yselkowitz** [comment]
Our pungi configs and comps are now in sync with c10s, and procps-ng-devel is in CRB on all arches in the latest compose.
