### ISSUE TITLE
TASK: Review packages using %eln

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#181]
### What does the ELN SIG need to do?
* By policy, the use of the `%{eln}` RPM variable is meant to be restricted and only permitted with approval.

As of this writing, the following packages are using it:

```
crun.spec
fedora-logos.spec
fedora-release.spec
fedora-repos.spec
freeipa.spec
ImageMagick.spec
iproute.spec
kernel.spec
libreport.spec
lynx.spec
mock-core-configs.spec
MUMPS.spec
netcat.spec
openbabel.spec
openscap.spec
pcs.spec
perl-DBD-MySQL.spec
python-aioquic.spec
python-pylsqpack.spec
subversion.spec
texlive-base.spec
virt-v2v.spec
```

We need to look through them, identify which ones are valid (adding these to a public list somewhere) and fixing the ones that should be `%{rhel}`.

**Comment by sgallagher** [comment]
This list was generated by grepping for `eln\}` against the extracted https://pkgs.fedoraproject.org/repo/rpm-specs-latest.tar.xz

**Comment by hroncok** [comment]
python-rpm-macros use it, but not in the spec

**Comment by hroncok** [comment]
mock-core-configs uses %eln to make the eln config the default one. With %rhel, it makes centos-stream or alma config the default. While I might have questions about the %rhel behavior, the %eln case is correct IMHO.

Furthermore, the package is not included in ELN.

**Comment by yselkowitz** [comment]
https://src.fedoraproject.org/rpms/openscap/blob/rawhide/f/openscap.spec#_63 is doubly wrong :-(
```
%if 0%{?rhel} && ! 0%{?eln}
BuildRequires:  epel-rpm-macros
%endif
```

**Comment by yselkowitz** [comment]
> [python-rpm-macros use it](https://github.com/fedora-eln/eln/issues/73), but not in the spec

Given the issues this causes when bootstrapping a new version of CS/RHEL, I would like to reexamine this.

**Comment by yselkowitz** [comment]
> > [python-rpm-macros use it](https://github.com/fedora-eln/eln/issues/73), but not in the spec
> 
> Given the issues this causes when bootstrapping a new version of CS/RHEL, I would like to reexamine this.

e.g. could this be as simple as:
```diff
@@ -77,4 +77,7 @@
 %package -n     %{python_wheel_pkg_prefix}-%{pypi_name}-wheel
 Summary:        The Python wheel module packaged as a wheel
+%if "%{python_wheel_pkg_prefix}" != "python%{python3_pkgversion}"
+Provides:       python%{python3_pkgversion}-wheel-wheel = %{version}-%{release}
+%endif
 %{bundled}
 
```

**Comment by hroncok** [comment]
I am sorry, but I don't understand how that solves the problem with different paths.

**Comment by hroncok** [comment]
(Perhaps this would be better discussed in a separate ticket.)

**Comment by yselkowitz** [comment]
My analysis:
- [ ] crun: should be `rhel` for disabling wasm; CHANGE.
- [ ] fedora-logos: theoretically should be `rhel` for disabling KDE themes, but is a Fedora-specific package; ALLOW?
- [ ] fedora-release: Fedora-specific package, ELN-specific necessary code; ALLOW.
- [ ] fedora-repos: Fedora-specific package, ELN-specific necessary code; ALLOW.
- [ ] freeipa: guards system-logos-ipa dependency which is not provided by fedora-logos; ALLOW.
- [ ] ImageMagick: false positive from changelog entry; IGNORE.
- [ ] iproute: guards a RHEL-specific source file, which actually prevents this from building during bootstrapping without modification; CHANGE.
- [ ] kernel: selects Fedora signing process instead of RHEL process; ALLOW.
- [ ] libreport: selects Fedora bug-reporting methods instead of RHEL methods; ALLOW.
- [ ] lynx: guards a RHEL-specific dependency on redhat-indexhtml; ALLOW.
- [ ] mock-core-configs: ELN-specific necessary code; ALLOW.
- [ ] MUMPS: should be `0%{?rhel} > ??` for building with flexiblas and disabling openmpi on ix86; CHANGE.
- [ ] netcat: kludge to prevent building for ELN in favour of nmap-ncat; ALLOW?
- [ ] openbabel: should be `0%{?rhel} > ??` for building with newer gcc; CHANGE.
- [x] openscap: FIXED.
- [ ] pcs: should be `0%{?rhel} >= ??` for various options; CHANGE.
- [ ] perl-DBD-MySQL: obsolete determination between community-mysql and mysql; CHANGE.
- [ ] python-aioquic: should be `0%{?rhel} > ??` for building with pyproject macros; CHANGE.
- [ ] python-pylsqpack: should be `0%{?rhel} > ??` for building with pyproject macros; CHANGE.
- [ ] subversion: should be just `0%{?rhel}` for disabling kwallet; CHANGE.
- [ ] texlive-base: theoretically should be changed to `rhel` for disabling xindy, but this package is blocked in ELN in favour of the ELN-branched texlive; CHANGE on principle? 
- [ ] virt-v2v: guards dependency on RHEL-specific libguestfs-winsupport; ALLOW.

**Comment by sgallagher** [comment]
@yselkowitz I'm not sure I have the background on the `iproute` usage; could you dig into that and file a BZ if appropriate?

**Comment by yselkowitz** [comment]
> (freeipa) Had to look this one up; I guess the idea is that it only pulls in the IPA (not FreeIPA) logos if it's building on real RHEL. I'm not sure if this is correct wrt to CentOS Stream, though.

Both centos-logos and redhat-logos have a -ipa subpackage which Provides: system-logos-ipa; fedora-logos does not.  Therefore, `0%{?rhel} >= 8 && ! 0%{?eln}` is correct across the board.

> (netcat) I don't think this is an acceptable usage. We can mark it as UNWANTED in the Content Resolve or we can prevent it from being built by explicitly disabling it in the EBS configuration (or both).

netcat is already blocked in EBS, and fedora-release-eln has a Suggests: nmap-ncat to point to the desired provider of /usr/bin/nc.  Is that enough?

**Comment by sgallagher** [comment]
> > (freeipa) Had to look this one up; I guess the idea is that it only pulls in the IPA (not FreeIPA) logos if it's building on real RHEL. I'm not sure if this is correct wrt to CentOS Stream, though.
> 
> Both centos-logos and redhat-logos have a -ipa subpackage which Provides: system-logos-ipa; fedora-logos does not. Therefore, `0%{?rhel} >= 8 && ! 0%{?eln}` is correct across the board.
> 

Ack, thanks.

> > (netcat) I don't think this is an acceptable usage. We can mark it as UNWANTED in the Content Resolve or we can prevent it from being built by explicitly disabling it in the EBS configuration (or both).
> 
> netcat is already blocked in EBS, and fedora-release-eln has a Suggests: nmap-ncat to point to the desired provider of /usr/bin/nc. Is that enough?

Yes, I think that should be sufficient.

**Comment by yselkowitz** [comment]
New usage to unbreak the ELN buildroot wrt openssl: https://src.fedoraproject.org/rpms/openssl/pull-request/57

**Comment by yselkowitz** [comment]
Three identical new usages have arisen:

- [ ] podman: workaround for deficiencies in c9s go-rpm-macros, should not be needed in c10s+; CHANGE
- [ ] podman-tui: ditto: CHANGE
- [ ] prometheus-podman-exporter: ditto; CHANGE

**Comment by yselkowitz** [comment]
Found some more:

- [ ] podman: allow gvisor-tap-vsock-gvforwarder to be a weak dependency on RHEL/CS only, but probably best it remain a hard dep for ELN so that it stays in the dep tree and is branched for RHEL etc.; ALLOW
- [ ] podman-tui: obsolete handling of deficiencies in c9s go-rpm-macros; CHANGE
- [ ] prometheus-podman-exporter: ditto; CHANGE

And one I thought had been previously mentioned but wasn't:

- [x]  scap-security-guide: RHEL-specific subpackage (even CS is excluded); ALLOW

**Comment by yselkowitz** [comment]
Filed PRs for those two, and one more:

- [ ] numpy: use `0%{?rhel} > NN` conditional; CHANGE

That leaves the following with justifiable usage of `%eln`:

- fedora-logos
- fedora-release
- fedora-repos
- freeipa
- kernel
- libreport
- lynx
- mock-core-configs
- openssl
- podman
- scap-security-guide
- virt-v2v

@sgallagher do you concur?  Should this be documented somewhere?

**Comment by sgallagher** [comment]
> Found some more:
> 
>     * [ ]  podman: allow gvisor-tap-vsock-gvforwarder to be a weak dependency on RHEL/CS only, but probably best it remain a hard dep for ELN so that it stays in the dep tree and is branched for RHEL etc.; ALLOW

I disagree, actually. If it's a weak dep in RHEL, then if we want it branched for RHEL it should be added explicitly to a Content Resolver workflow. It's just as likely that the reason it's a weak dep is that they do NOT want it branched for RHEL and instead want to support it if it's added to EPEL.

The others I agree with.




> Filed PRs for those two, and one more:
> 
>     * [ ]  numpy: use `0%{?rhel} > NN` conditional; CHANGE
> 
> 
> That leaves the following with justifiable usage of `%eln`:
...
> @sgallagher do you concur? Should this be documented somewhere?

Yes, we should add a page to the ELN docs (at the same sublevel as https://docs.fedoraproject.org/en-US/eln/ftbfs/) and link to it from the FAQ on the subject of the macro.

**Comment by yselkowitz** [comment]
gvisor-tap-vsock was just added in 9.4, and is certainly wanted for 10.  Digging further into this, the weak dependency was intended to be a temporary situation, and upstream has already changed podman.spec wrt this dependency, so the point is moot as it will go away in due course.
