### ISSUE TITLE
TASK: Do not run composes if nothing changed from the previous compose

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-eln/eln#203]
### What does the ELN SIG need to do?
Composes are expensive and time-consuming, and running a compose [when literally nothing has changed](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/JSD2KMMSALLEKOQXQVCQ6LDRSFYQMJEK/) is wasteful. Some kind of mechanism should be developed to determine whether any content changed from the previous compose to the pending one and cleanly stop going any further if it is determined there is no content change.

**Comment by sgallagher** [comment]
I don't think this is practically possible.

The compose is made up of a number of different inputs, any one of which can result in different output: the set of packages in the `eln` tag, the contents of the `eln` branch of pungi-fedora, the contents of the ELN comps.xml definition, the contents of fedora-kiwi-definitions and more. Just because the set of packages hasn't changed doesn't necessarily mean that nothing about the compose changed.

Furthermore, we can't easily discover which packages have changed until we've at least done the first half of the compose: gathering the packages and turning them into a repository and install tree. At that point, we've already done quite a bit of the work.

So, at best I think we could have the reporting script just elect not to send the email to the devel list if the set of packages and images is unchanged, but I'm not sure that's even worth it, given that it's a rare occurrence.

**Comment by Conan-Kudo** [comment]
We don't need to produce the repository or install tree to determine that we don't need to do anything. The package gathering should be sufficient enough to know whether the set of inputs has changed. We also can check for a new head commit for all the other things too.

**Comment by yselkowitz** [comment]
Does rawhide do any of that?

**Comment by sgallagher** [comment]
> Does rawhide do any of that?

No, because I don't think there's ever been a day where nothing changed in Rawhide.



> We don't need to produce the repository or install tree to determine that we don't need to do anything. The package gathering should be sufficient enough to know whether the set of inputs has changed. We also can check for a new head commit for all the other things too.

I don't think the gain is worth the effort, since it's quite rare for nothing to change between two composes. If someone wants to contribute code to do it, I'll happily review it, but I don't think it's worth prioritizing effort on at this time.

**Comment by yselkowitz** [comment]
IIRC there has been only one other 0-change day, and it brought attention to the fact that the automation was not processing new packages.  Given the usual pace of rawhide (and hence ELN) it should be a rare occurrence in any case, but possibly worthy of investigation if/when it happens again.  Given that and the lack of precedent, I don't think we should do anything here.
