### ISSUE TITLE
Rate-limit the eln-periodic task

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#31]
As noted in [this](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/AVFI3WEXYIEK2WXEHERBABDN6ZJU3MPJ/) Fedora Devel thread, the number of attempts to rebuild failed packages is unnecessarily high. We should implement a ramp-down mechanism to reduce the rate at which individual packages are retried.

**Comment by bookwar** [comment]
The current (very simple) rate logic is implemented 

There is a cron configuration to run eln-periodic job (currently every hour).
And then there is LIMIT value which controls how many rebuilds the periodic job will trigger(currently 10).

We create a list of components we need to rebuild, randomize them, then take $LIMIT number of items from the top of the list and trigger rebuilds.

There is also "on hold" list, so that some packages or package prefixes can be excluded from the rebuild loop. We will still attempt to build new version of such packages on update in Fedora Rawhide.

Example change of these configuration options is here:

 https://github.com/fedora-ci/eln-periodic/commit/f34bcebc03b557cc2c0acec7f4b4d7352ecf3795
