### ISSUE TITLE
Missing package git-core at the repository

### ISSUE THREAD

**Issue by juanje** [fedora-eln/eln#38]
At the Red Hat CKI team (https://cki-project.org/) we're building containers images (based on ELN) to run kernel tests for ELN, but since yesterday started to break due a missing package (`git-core`). It happens with all architectures we test (`amd64`, `arm64`, `ppc64le` and `s390x`).

Here is the error: 
```
[MIRROR] git-core-2.30.1-2.eln110.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/AppStream/x86_64/os/Packages/git-core-2.30.1-2.eln110.x86_64.rpm (IP: 140.211.169.206)
```
The full log is here: https://gitlab.com/cki-project/containers/-/jobs/1127107006

I checked the mirror and there is no package `git-core`, nor that version nor other. As `dnf` try to fetch the package from that location, I guess the package is indexed, but is missing from the repo.

**Comment by sgallagher** [comment]
It has been 26 days since we had a successful ELN compose, due to a series of issues. I'll look into it.

**Comment by juanje** [comment]
@sgallagher I've realized that the build of the base system we do (we build our own base container because of this issue #16 ) has failed due another missing package (`glib2`):

```
[MIRROR] glib2-2.67.4-2.eln110.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/glib2-2.67.4-2.eln110.x86_64.rpm (IP: 152.19.134.198)
```
The full log is here: https://gitlab.com/cki-project/containers/-/jobs/1131299566#L1138

**Comment by jkonecny12** [comment]
Hi @sgallagher , is there something to be done to stabilize the ELN composes? Anything we can do (Anaconda team)?

Right now, it's not really happy situation, our ELN tests are most of the time failing. I'm starting to think about disabling them because of the failure rate. I would try to solve this by creating some repository syncing to have a fallback but that wouldn't solve Packit which is using COPR.

If there is anything please contact me, feel free to ping me about anything where we could help you.

Yeah, and I know I should file the issue much sooner myself. Will do that next time... maybe that would help the situation?

**Comment by sgallagher** [comment]
@jkonecny12 I'm looking into it now. It looks like the latest problem is due to the xorg-x11-server-utils being split out into multiple packages; our lorax config is inheriting from RHEL 9's config which still uses the old name. I've got Jan Kaluza looking at it.

Going forward, we're looking at getting a compose success/failure dashboard up so members of the ELN SIG can spot when it's broken and fix it sooner.

**Comment by jkonecny12** [comment]
Seems to be working correctly for us now. Thanks a lot!

**Comment by juanje** [comment]
@sgallagher Thanks for everything, it seems to be working fine for us as well! :smiley:
