### ISSUE TITLE
Update gcc to gcc11 in ELN

### ISSUE THREAD

**Issue by bookwar** [fedora-eln/eln#8]
We are going to use gcc11 in ELN ahead of Rawhide.

We have gcc11 buildt in a sidetag which we need to merge in the ELN. And then we should run a mass rebuild of ELN packages

**Comment by bookwar** [comment]
The sidetag with the update is available via https://bodhi.fedoraproject.org/updates/FEDORA-2020-44d2abaa1b

Missing steps:
1) packages need to be excluded from the rebuild automation in https://github.com/fedora-ci/eln-periodic/blob/master/eln-check.py#L92
2) we need to decide on when doe we do the Mass rebuild

**Comment by jakubjelinek** [comment]
For the exclusion from automation, I think we only need to exclude gcc, libtool and annobin shouldn't be diverging from rawhide, so it should be ok if they keep to be updated from rawhide.  All we need to ensure is that these are tagged into eln before somebody rebuilds them in rawhide.

**Comment by jakubjelinek** [comment]
https://github.com/fedora-ci/eln-periodic/pull/16 for exclusion of gcc.

**Comment by jakubjelinek** [comment]
As for mass rebuild, I think it would be wise not to do it immediately, but at least for a few days just rebuild with is rebuilt in rawhide.  That is what has been used in rawhide too for years, usually at least a week or two of voluntary rebuilds before doing a mass rebuild.
While Jeff Law has done test mass rebuilds with recent gcc 11 snapshots, they've only been done on x86_64.

**Comment by JeffreyALaw** [comment]
I don't expect we'll be diverging at a source level for libtool or annobin/annocheck.  So if we need to rebuild them for ELN  (say due to options twiddling in gcc), we should be able to trigger that by doing something like a release # bump in Fedora which in turn would trigger an ELN rebuild.

For mass rebuilding.  Yes, my tester has only been testing gcc-11 on x86_64 and I fully expect some target specific issues like we get at every major release update (particularly s390x).   I'd let the ELN  team determine when they want to start building.  It's probably very soon given the schedules I've heard.

I'm set up to run aarch64 tests easily, it wouldn't be hard to fire that up and let it run -- while s390x mass testing would be far more useful than aarch64 it's just much easier to get sufficient aarch64 resources in the quantities I need.

Having been building Fedora with gcc-11 and LTO, I'm probably in the best position to do any first level triage, but we also want Jakub cc'd.  Jakub -- we should consider the team as a whole at our disposal if we run into more than either of us can handle.

**Comment by fweimer** [comment]
Currently, `redhat-rpm-config` does not specify the desired x86-64 build flags for ELN. I would like to change this before the mass-rebuild as possible. This change would have to be specific to ELN non-Clang builds (Clang won't be ready before LLVM 12).

**Comment by bookwar** [comment]
@sgallagher I assume you are going to trigger the mass rebuild in the sidetag before we land this change directly in ELN?

**Comment by sgallagher** [comment]
The mass rebuild is now running in `eln-build-side-32813`.

**Comment by bookwar** [comment]
Comparison between rawhide and the sidetag:
```
Date: 2020-10-26 21:15:42.847314
Source1: f34
Source2: eln-build-side-32813
ERROR: 2
SAME: 4157
NONE: 181   // build is missing - most likely a failure
NEW: 52    // build in sidetag exists and is newer than in rawhide
OLD: 30    // build in sidetag exists is older than in rawhide
EXTRA: 2  
total: 4424
```
[status.txt](https://github.com/fedora-eln/eln/files/5441383/status.txt)

**Comment by bookwar** [comment]
@JeffreyALaw I posted the PR with the script `compare.py` which creates the test report: https://github.com/fedora-eln/eln/pull/10

I don't want to merge it as is, but you can checkout the branch and use it directly for now.

**Comment by fweimer-rh** [comment]
Has this concluded? GCC 11 is in ELN, but I still see a version discrepancy:

```
$ koji latest-build eln annobin binutils gcc
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
annobin-9.46-2.eln105                     eln                   jakub
binutils-2.35.1-16.eln107                 eln                   sgallagh
gcc-11.0.0-0.6.eln105                     eln                   jakub
$ koji latest-build f34 annobin binutils gcc
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
annobin-9.52-2.fc34                       f34                   nickc
binutils-2.35.1-16.fc34                   f34                   fweimer
gcc-11.0.0-0.7.fc34                       f34                   jakub
```

**Comment by contyk** [comment]
All these have been built with gcc-11 but for some reason they're not up-to-date. Ping @sgallagher.

**Comment by sgallagher** [comment]
Looks like they were built in a side tag by Jakub *after* I merged the original.

**Comment by sgallagher** [comment]
Oh, and we still have them excluded from automatic sync; I forgot to change that back when we merged. I'll send a PR shortly.

**Comment by sgallagher** [comment]
https://github.com/fedora-ci/eln-periodic/pull/22 should fix GCC going forward.

It looks like annobin failed because clang failed to build. I'm not sure why yet.
