### ISSUE TITLE
TASK: Switch x86_64 baseline to x86-64-v3

### ISSUE THREAD

**Issue by fweimer-rh** [fedora-eln/eln#83]
I would like to propose to update the baseline for the x86_64 ELN architecture to x86-64-v3. This enables the more compact VEX instruction encoding, FMA (fused multiply and add), and various bit manipulation instructions. Together with auto-vectorization at `-O2` in GCC 12, we also expect some nice benefit from AVX and AVX2, too.

I believe the Fedora ELN builders are ready for this. (They would even be compatible with x86-64-v4, but it's obviously too soon for that.) I expect switch the ELN baseline will be helpful to a future downstream effort to change the baseline, but of course no firm determination of the direction to take has been made at this early stage.

To be absolutely clear, this is rather different from #78 and #79: With the change proposed here, we will be moving past the current downstream requirement (x86-64-v2), not merely catching up to it.

**Comment by berrange** [comment]
Some input from the virtualization side. Note I'm NOT giving an opinion for or against this proposal, I'm merely going to present the technical facts wrt QEMU/KVM 

The following page shows compatibility of the different QEMU CPU models with the x86 baselines:

  https://www.qemu.org/docs/master/system/i386/cpu.html

We see that compared to the current x86_64-v2, switching to x86_64-v3 baseline eliminates support for the following QEMU / KVM CPU models:

 * Denverton
 * IvyBridge
 * Nehalem
 * Opteron_G4
 * Opteron_G5
 * SandyBridge
 * Snowridge
 * Westmere

IOW, for Intel hosts it will require Haswell as the minimum (2013 vintage) and for AMD hosts it will require EPYC (2017 vintage).

A small caveat is that with the v3 baseline there is no named QEMU/KVM CPU model users can pick that is capable of running on both Intel and AMD hosts, while also satisfying the v3 baseline. This means if a user needs to pick a CPU for a VM without knowing what host vendor it will run on, the only choice is to request host-passthrough or host-model. With v2, a user in this scenario could have picked Nehalem and its featureset was able to run guests on any Intel or AMD host compatible with v2. . 

Perhaps a more significant problem is that QEMU's emulation layer (TCG) is incapable of supporting the v3 baseline as it does not have support for emulating all the required features for the Intel and AMD guest CPUs models compatible with v3:

```
$ qemu-system-x86_64 -accel tcg  -cpu Haswell-noTSX,enforce  -display none
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.fma [bit 12]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.f16c [bit 29]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx2 [bit 5]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.invpcid [bit 10]
qemu-system-x86_64: TCG doesn't support requested features

$ qemu-system-x86_64 -accel tcg  -cpu EPYC,enforce  -display none
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.fma [bit 12]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.f16c [bit 29]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.avx2 [bit 5]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.rdseed [bit 18]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.07H:EBX.sha-ni [bit 29]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.fxsr-opt [bit 25]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.80000001H:ECX.misalignsse [bit 7]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.80000001H:ECX.3dnowprefetch [bit 8]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.80000001H:ECX.osvw [bit 9]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.80000001H:ECX.topoext [bit 22]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.8000000AH:EDX.nrip-save [bit 3]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.0DH:EAX.xsavec [bit 1]
qemu-system-x86_64: TCG doesn't support requested features
```

Unfortunately I'm not aware of anyone upstream in QEMU actively working towards closing these gaps.

Ideally of course people would just be able to used nested hardware virtualization instead of falling back to emulation, but that's still (frustratingly) not as reliably available as one would like it to be. 

The scenario where this matters would be if using a ELN virtual machine in the cloud, and wanting to use libguestfs (guestfish and various other tools), to interact with a disk image. This would require either nested hardware virt or TCG emulation.

**Comment by sgallagher** [comment]
This was approved in [today's ELN meeting](https://meetbot.fedoraproject.org/fedora-meeting/2023-03-10/eln.2023-03-10-17.02.html):

* x86_64-v3 as the architecture baseline for RHEL 10  (sgallagh,
  17:10:17)
  * LINK:
    https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/247
    (sgallagh, 17:16:59)
  * QEMU 7.2+ should be able to emulate x86_64-v3 hardware, but may have
    bugs to watch out for. Some packages like libguestfs have tests that
    rely on emulated CPUs and may be affected by this change.
    (sgallagh, 17:26:54)
  * AGREED: The ELN SIG approves the change of baseline to x86_65-v3
    (sgallagh, 17:28:35)
  * AGREED: No mass-rebuild is required immediately for this change. It
    can wait until the Fedora 39 scheduled rebuild.
    (sgallagh, 17:30:36)
